baseURL = "https://kevindienst.blog"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Kevin Dienst's Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Kevin Dienst's Blog"
author = "Kevin Dienst"
description = "RPGs, Board games, and Python! 🐍"
profilePicture = "images/avatar.jpg"
displayMode = "dark"
# Required for Chroma Hugo Syntax Highlighting
customCss = ["css/syntax.css"]

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/axi0m"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/kevindienst"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/kevindienst"
